### ISSUE TITLE
Tether_07.jl: oberservations

### ISSUE THREAD

**Issue by johhell** [ufechner7/Tethers.jl#4]
I'm not sure, but I found some points are not clear for me:

## calculation of tether cross-section
`mass_per_meter = se.rho_tether * se.segments * (se.d_tether/2000.0)^2`
correct:  ` mass_per_meter = se.rho_tether * pi * (se.d_tether/2000.0)^2    # rho * cross-section`

## chain model
see commit:  https://github.com/johhell/Tethers.jl/commit/e9a3c40fc14b6d0587683795730b25c1d8e57d7a

Some details: there are N segments with (N+1) nodes with masses. Therefore (N+1) forces are needed to calculate the acceleration. For the first and last node the formulas are different. For all other, segment-forces from spring/damper are added.

I checked the revised model with my Modia3D model and received the same results.

**Comment by ufechner7** [comment]
Feel free to create a pull request!

**Comment by ufechner7** [comment]
I fixed the calculation of mass_per_meter. Thanks for finding this bug!

**Comment by ufechner7** [comment]
I tried to fix all issues. Still missing: A set of unit tests. I make a separate issue for that.
